# Site settings
title: PIC16B
subtitle: Python with Applications II
description: 
baseurl: "/PIC16B/" # the subpath of your site, e.g. /blog/
url: "http://philchodrow.github.io/PIC16B" # the base hostname & protocol for your site
syllabus: "http://philchodrow.github.io/PIC16B/syllabus/"
materials: "http://philchodrow.github.io/PIC16B/materials/"
resources: "http://philchodrow.github.io/PIC16B/resources/" 
schedule: "http://philchodrow.github.io/PIC16B/schedule/"
project: "http://philchodrow.github.io/PIC16B/project/"
assignments: "http://philchodrow.github.io/PIC16B/assignments/"
tips:  "http://philchodrow.github.io/PIC16B/tips/"
involved: "http://philchodrow.github.io/PIC16B/involved/"
githubdir: "philchodrow/PIC16B"

# Author/user information
email: phil@math.ucla.edu
twitter_username: philchodrow
github_username:  philchodrow
authorurl: "http://www.philchodrow.com"
address: |
    Department of Mathematics
    UCLA


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
